name: my-first-workflow
on:
  push:

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: running commands
        run: |
          pwd
          ls -lrth
          hostname
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: running commands
        run: |
          echo `pwd` >> myartifact.txt
          mkdir artifact
          echo `ls -lrth` >> artifact/myartifact2.txt
          echo `hostname` >> artifact/myartifact3.txt
#upload artifactory
      - name: upload single file
        uses: actions/upload-artifact@v7.0.1
        with:
          name: single_file
          path: ./myartifact.txt
      - name: upload multiple artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: directory_artifact
          path: |
            ./myartifact.txt
            artifact/
#download artifactory
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: check directory
        run: |
          pwd
          ls -lrth
      - name: download artifactory
        uses: actions/download-artifact@v5
        with:
          name: single_file
      - name: check the artifactory
        run: ls -lrth

          
